name: Kubernetes Infrastructure
description: Kubernetes based infrastructure including logging, monitoring and database
requirements:
  - kubectl
  - npm
install_script:
  - os: darwin
    script: install.sh
  - os: linux
    script: install.sh
run_script:
  - os: darwin
    script: run.sh
  - os: linux
    script: run.sh

properties:
  - name: stack
    type: string
    description: Pulumi stack name
    required: true
  - name: project_name
    type: string
    description: Name of your project
    required: true
  - name: host
    type: string
    description: Host/Domain name of the application (need for ingress rules, use "localhost" for local development)
    required: true
  - name: use_vpn
    type: boolean
    description: Use VPN to access cluster resources (not just exposed ones)
    required: true
  - name: use_db
    type: boolean
    description: Configure database access
    required: true
    requires:
      - install_self_hosted_db

#    Docker registry
  - name: create_image_pull_secret
    type: boolean
    description: Create image pull secret
    required: true
    requires:
      - registry_url
      - registry_username
      - registry_password
  - name: registry_url
    type: string
    description: Docker registry URL
    required: false
  - name: registry_username
    type: string
    description: Docker registry username
    required: false
  - name: registry_password
    type: password
    description: Docker registry password
    required: false

#    DB
  - name: install_self_hosted_db
    type: boolean
    description: Install self hosted MySQL database
    required: false
    requires:
      - db_name
      - db_username
      - db_password
  - name: db_url
    type: string
    description: Database server URL (blank if using self hosted DB)
    required: false
  - name: db_name
    type: string
    description: Database name
    required: false
  - name: db_username
    type: string
    description: Database username
    required: false
  - name: db_password
    type: password
    description: Database password
    required: false
